name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # 注意替换下方的 HF_USERNAME 为你的用户名，SPACE_NAME 为你的 Space 名称
        run: git push --force https://frankmes:$HF_TOKEN@huggingface.co/spaces/frankmes/vlm main
